spring.application.name=SpringAIDemo

# While Working with OpenAI Uncomment it and set an API key - (Paid)
#spring.ai.openai.chat.options.model=gpt-4o
#spring.ai.openai.api-key=<YOUR_API_KEY>
#spring.ai.openai.embedding.options.model=text-embedding-3-large


# While Working Gemini Uncomment it and set an API key (Free)
#spring.ai.openai.api-key=<YOUR_API_KEY>
#spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
#spring.ai.openai.chat.completions-path=/chat/completions
#spring.ai.openai.chat.options.model=gemini-2.5-flash
#spring.ai.model.embedding.text=google-genai
#spring.ai.google.genai.embedding.api-key=<YOUR_API_KEY>
#spring.ai.google.genai.embedding.text.options.model=text-embedding-004


