spring.application.name=SpringAIDemo

# While Working with OpenAI Uncomment it and set an API key - (Paid)
#spring.ai.openai.chat.options.model=gpt-4o
#spring.ai.openai.api-key=<YOUR_OPENAI_API_KEY>

# While Working Gemini Uncomment it and set an API key (Free)
#spring.ai.openai.api-key=<YOUR_GEMINI_API_KEY>
#spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
#spring.ai.openai.chat.completions-path=/chat/completions
#spring.ai.openai.chat.options.model=gemini-2.5-flash

