spring.application.name=mcp_demo
spring.ai.openai.api-key=<your-api-key>


#spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
spring.ai.mcp.client.sse.connections.spring-ai-mcp.url=http://localhost:8282
